- name: Add 'admin' user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}" # Ajoute l'utilisateur de connexion au groupe docker
    groups: docker
    append: yes

# --- TÂCHES D'INSTALLATION DE DOCKER (Les 8 tâches du Playbook initial) ---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-venv
    state: latest
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Install Python3 and pip3
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Create a virtual environment for Docker SDK
  ansible.builtin.command: python3 -m venv /opt/docker_venv
  args:
    creates: /opt/docker_venv

- name: Install Docker SDK for Python in virtual environment
  ansible.builtin.command: /opt/docker_venv/bin/pip install docker

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
  tags: docker