- name: Run API Container
  community.docker.docker_container:
    name: tp-api
    image: blaina/tp-devops-simple-api:latest # VOTRE IMAGE API
    state: started
    ports:
      - "8080:8080"
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tp-db:5432/devops_db
      SPRING_DATASOURCE_USERNAME: devops_user
      SPRING_DATASOURCE_PASSWORD: devops_password
      SERVER_PORT: "8080"
    networks:
      - name: tp-devops-network
    depends_on:
      - tp-db