version: '3.8' 

services:
  
  database:
    build: ./database 
    container_name: postgres-db
    networks:
      - app-network  
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

 
  backend:
    build: ./simpleapi 
    container_name: backend-api
    networks:
      - app-network  
    depends_on:
      - database     
    environment:
      
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  
  httpd:
    build: ./httpd
    container_name: httpd-server
    ports:
      - "80:80" 
    networks:
      - app-network  
    depends_on:
      - backend      
    restart: always

networks:
  app-network:
    driver: bridge 

volumes:
  pgdata: 